services:
  boltz:
    hostname: boltz
    depends_on:
      - lnd-2
      - elementsd
      - bitcoind
      - anvil
    restart: always
    image: boltz/boltz:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/lnd-2:/data/lnd/
      - ./data/boltz/:/root/.boltz/
      - ./data/elements/:/root/.elements/

  anvil:
    hostname: anvil
    image: ghcr.io/foundry-rs/foundry:latest
    command:
      - anvil --host 0.0.0.0
    ports:
      - 8545:8545

  bitcoind:
    hostname: bitcoind
    restart: always
    image: boltz/bitcoin-core:24.0.1
    command:
      - -regtest
      - -fallbackfee=0.00000253
      - -zmqpubrawtx=tcp://0.0.0.0:29000
      - -zmqpubrawblock=tcp://0.0.0.0:29001
      - -txindex
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -rpcuser=regtest
      - -rpcpassword=regtest
    expose:
      - 29000
      - 29001
      - 18443
      - 18444
    volumes:
      - ./data/bitcoin:/root/.bitcoin

  elementsd:
    hostname: elements
    restart: always
    image: ghcr.io/vulpemventures/elements:22.1.1
    depends_on:
      - bitcoind
    expose:
      - 18884
      - 31000
      - 31001
      - 31002
    volumes:
      - ./data/elements/elements.conf:/home/elements/.elements/elements.conf

  clightning-1:
    hostname: clightning-1
    restart: always
    depends_on:
      - bitcoind
    image: boltz/c-lightning:23.08.1
    command:
      - --large-channels
      - --network
      - regtest
      - --bind-addr=0.0.0.0:9735
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcport=18443
      - --bitcoin-rpcuser=regtest
      - --bitcoin-rpcpassword=regtest
      - --grpc-port=9736
      - --dev-bitcoind-poll=3
    expose:
      - 9735
    ports:
      - 9736:9736
    volumes:
      - ./data/clightning-1:/root/.lightning/

  lnd-1:
    hostname: lnd-1
    depends_on:
      - bitcoind
    image: boltz/lnd:0.17.0-beta
    restart: always
    command:
      - --listen=lnd-1:9735
      - --rpclisten=lnd-1:10009
      - --restlisten=lnd-1:8081
      - --bitcoin.active
      - --bitcoin.regtest
      - --bitcoin.node=bitcoind
      - --bitcoind.rpchost=bitcoind
      - --bitcoind.zmqpubrawtx=bitcoind:29000
      - --bitcoind.zmqpubrawblock=bitcoind:29001
      - --bitcoind.rpcuser=regtest
      - --bitcoind.rpcpass=regtest
      - --noseedbackup
      - --protocol.wumbo-channels
    expose:
      - 8081
      - 9735
      - 10009
    ports:
      - 8081:8081
      - 10009:10009
    volumes:
      - ./data/lnd-1:/root/.lnd/

  lnd-2:
    hostname: lnd-2
    depends_on:
      - bitcoind
    image: boltz/lnd:0.17.0-beta
    restart: on-failure
    command:
      - --listen=lnd-2:9735
      - --rpclisten=lnd-2:10009
      - --restlisten=lnd-2:8081
      - --bitcoin.active
      - --bitcoin.regtest
      - --bitcoin.node=bitcoind
      - --bitcoind.rpchost=bitcoind
      - --bitcoind.zmqpubrawtx=bitcoind:29000
      - --bitcoind.zmqpubrawblock=bitcoind:29001
      - --bitcoind.rpcuser=regtest
      - --bitcoind.rpcpass=regtest
      - --noseedbackup
      - --protocol.wumbo-channels
    expose:
      - 8081
      - 9735
      - 10009
    volumes:
      - ./data/lnd-2:/root/.lnd/

  mempool-web:
    restart: always
    depends_on:
      - mempool-api
    environment:
      FRONTEND_HTTP_PORT: 8090
      BACKEND_MAINNET_HTTP_HOST: mempool-api
      BACKEND_MAINNET_HTTP_PORT: 8999
      NGINX_HOST: mempool-api
      NGINX_PORT: 8999
      LIQUID_ENABLED: true
      LIQUID_WEBSITE_URL: http://localhost:8091
    image: mempool/frontend:latest
    ports:
      - 8090:8090

  electrs:
    hostname: electrs
    restart: always
    image: blockstream/esplora:electrs-latest
    entrypoint: ./electrs_bitcoin/bin/electrs
    command:
      - --electrum-rpc-addr
      - electrs:19001
      - --http-socket-file
      - /data/.electrs/esplora-regtest
      - --daemon-rpc-addr
      - bitcoind:18443
      - --daemon-dir
      - /home/elements/.elements
      - --cookie
      - regtest:regtest
      - --network
      - regtest
      - --jsonrpc-import
      - -vvvv
    ports:
      - 19000:19000
      - 19001:19001
    volumes:
      - ./data/elements:/home/elements/.elements
      - ./data/electrs:/data/.electrs

  electrs-liquid:
    hostname: electrs-liquid
    restart: always
    image: blockstream/esplora:electrs-latest
    environment:
      ELECTRS_DAEMON_RPC_ADDR: bitcoind:18443
      ELECTRS_DAEMON_P2P_ADDR: bitcoind:18444
    entrypoint: ./electrs_liquid/bin/electrs
    command:
      - --electrum-rpc-addr
      - electrs-liquid:19002
      - --http-socket-file
      - /data/.electrs-liquid/esplora-liquid-regtest
      - --daemon-rpc-addr
      - elementsd:18884
      - --daemon-dir
      - /home/elements/.elements
      - --cookie
      - regtest:regtest
      - --network
      - liquidregtest
      - --parent-network
      - regtest
      - --jsonrpc-import
      - -vvvv
    ports:
      - 19002:19002
      - 19003:19003
    volumes:
      - ./data/elements:/home/elements/.elements
      - ./data/electrs-liquid:/data/.electrs-liquid

  mempool-api:
    hostname: mempool-api
    restart: always
    depends_on:
      - bitcoind
      - mempool-db
    image: mempool/backend:latest
    environment:
      REDIS_ENABLED: false
      BACKEND_HTTP_PORT: 8999
      MEMPOOL_BACKEND: esplora
      ESPLORA_UNIX_SOCKET_PATH: /data/.electrs/esplora-regtest
      CORE_RPC_HOST: bitcoind
      CORE_RPC_PORT: 18443
      CORE_RPC_USERNAME: regtest
      CORE_RPC_PASSWORD: regtest
      DATABASE_ENABLED: true
      DATABASE_HOST: mempool-db
      DATABASE_DATABASE: mempool
      DATABASE_USERNAME: mempool
      DATABASE_PASSWORD: mempool
    expose:
      - 8999
    ports:
      - 8999:8999
    volumes:
        - ./data/electrs:/data/.electrs

  mempool-db:
    hostname: mempool-db
    environment:
      MYSQL_DATABASE: mempool
      MYSQL_USER: mempool
      MYSQL_PASSWORD: mempool
      MYSQL_ROOT_PASSWORD: admin
    image: mariadb:10.5.8

  mempool-web-liquid:
    restart: always
    depends_on:
      - mempool-api-liquid
    environment:
      BASE_MODULE: liquid
      LIQUID_ENABLED: true
      BISQ_ENABLED: false
      MEMPOOL_WEBSITE_URL: http://localhost:8090
      FRONTEND_HTTP_PORT: 8091
      BACKEND_MAINNET_HTTP_HOST: mempool-api-liquid
      BACKEND_MAINNET_HTTP_PORT: 8998
      NGINX_HOST: mempool-api-liquid
      NGINX_PORT: 8998
    image: mempool/frontend:latest
    ports:
      - 8091:8091

  mempool-api-liquid:
    hostname: mempool-api-liquid
    restart: always
    depends_on:
      - elementsd
      - mempool-db-liquid
      - electrs-liquid
    image: mempool/backend:latest
    environment:
      BACKEND_HTTP_PORT: 8998
      MEMPOOL_NETWORK: liquid
      MEMPOOL_BACKEND: esplora
      ESPLORA_UNIX_SOCKET_PATH: /data/.electrs-liquid/esplora-liquid-regtest
      CORE_RPC_HOST: elementsd
      CORE_RPC_PORT: 18884
      CORE_RPC_USERNAME: regtest
      CORE_RPC_PASSWORD: regtest
      DATABASE_ENABLED: true
      DATABASE_HOST: mempool-db-liquid
      DATABASE_DATABASE: mempool
      DATABASE_USERNAME: mempool
      DATABASE_PASSWORD: mempool
    expose:
      - 8998
    ports:
      - 8998:8998
    volumes:
      - ./data/electrs-liquid:/data/.electrs-liquid

  mempool-db-liquid:
    hostname: mempool-db-liquid
    environment:
      MYSQL_DATABASE: mempool
      MYSQL_USER: mempool
      MYSQL_PASSWORD: mempool
      MYSQL_ROOT_PASSWORD: admin
    image: mariadb:10.5.8
