services:
  boltz:
    hostname: boltz
    depends_on:
      - lnd-2
      - elementsd
      - bitcoind
      - anvil
    restart: always
    image: boltz/boltz:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/lnd-2:/data/lnd/
      - ./data/boltz/:/root/.boltz/
      - ./data/elements/:/root/.elements/

  boltz-client:
    hostname: boltz-client
    depends_on:
      - clightning-2
      - boltz
    restart: always
    image: boltz/boltz-client:latest
    ports:
      - 9002:9002
      - 9003:9003
    volumes:
      - ./data/clightning-2:/root/.lightning/
      - ./data/boltz-client/:/root/.boltz/
      - ./data/elements/:/root/.elements/

  anvil:
    hostname: anvil
    image: ghcr.io/foundry-rs/foundry:latest
    command:
      - anvil --host 0.0.0.0
    ports:
      - 8545:8545

  bitcoind:
    hostname: bitcoind
    restart: always
    image: boltz/bitcoin-core:24.0.1
    command:
      - -regtest
      - -fallbackfee=0.00000253
      - -zmqpubrawtx=tcp://0.0.0.0:29000
      - -zmqpubrawblock=tcp://0.0.0.0:29001
      - -txindex
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -rpcuser=regtest
      - -rpcpassword=regtest
    expose:
      - 29000
      - 29001
      - 18443
      - 18444
    volumes:
      - ./data/bitcoin:/root/.bitcoin

  elementsd:
    hostname: elements
    restart: always
    image: ghcr.io/vulpemventures/elements:22.1.1
    depends_on:
      - bitcoind
    expose:
      - 18884
      - 31000
      - 31001
      - 31002
    volumes:
      - ./data/elements/elements.conf:/home/elements/.elements/elements.conf

  clightning-1:
    hostname: clightning-1
    restart: always
    depends_on:
      - bitcoind
    image: boltz/c-lightning:23.08.1
    command:
      - --large-channels
      - --network
      - regtest
      - --bind-addr=0.0.0.0:9735
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcport=18443
      - --bitcoin-rpcuser=regtest
      - --bitcoin-rpcpassword=regtest
      - --grpc-port=9736
      - --dev-bitcoind-poll=3
    expose:
      - 9735
    ports:
      - 9736:9736
    volumes:
      - ./data/clightning-1:/root/.lightning/

  clightning-2:
    hostname: clightning-2
    restart: always
    depends_on:
      - bitcoind
    image: boltz/c-lightning:23.08.1
    command:
      - --large-channels
      - --network
      - regtest
      - --bind-addr=0.0.0.0:9735
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcport=18443
      - --bitcoin-rpcuser=regtest
      - --bitcoin-rpcpassword=regtest
      - --grpc-port=9736
      - --dev-bitcoind-poll=3
    expose:
      - 9735
      - 9736
    volumes:
      - ./data/clightning-2:/root/.lightning/

  lnd-1:
    hostname: lnd-1
    depends_on:
      - bitcoind
    image: boltz/lnd:0.17.0-beta
    restart: always
    command:
      - --listen=lnd-1:9735
      - --rpclisten=lnd-1:10009
      - --restlisten=lnd-1:8081
      - --bitcoin.active
      - --bitcoin.regtest
      - --bitcoin.node=bitcoind
      - --bitcoind.rpchost=bitcoind
      - --bitcoind.zmqpubrawtx=bitcoind:29000
      - --bitcoind.zmqpubrawblock=bitcoind:29001
      - --bitcoind.rpcuser=regtest
      - --bitcoind.rpcpass=regtest
      - --noseedbackup
      - --protocol.wumbo-channels
    expose:
      - 8081
      - 9735
      - 10009
    ports:
      - 8081:8081
      - 10009:10009
    volumes:
      - ./data/lnd-1:/root/.lnd/

  lnd-2:
    hostname: lnd-2
    depends_on:
      - bitcoind
    image: boltz/lnd:0.17.0-beta
    restart: on-failure
    command:
      - --listen=lnd-2:9735
      - --rpclisten=lnd-2:10009
      - --restlisten=lnd-2:8081
      - --bitcoin.active
      - --bitcoin.regtest
      - --bitcoin.node=bitcoind
      - --bitcoind.rpchost=bitcoind
      - --bitcoind.zmqpubrawtx=bitcoind:29000
      - --bitcoind.zmqpubrawblock=bitcoind:29001
      - --bitcoind.rpcuser=regtest
      - --bitcoind.rpcpass=regtest
      - --noseedbackup
      - --protocol.wumbo-channels
    expose:
      - 8081
      - 9735
      - 10009
    volumes:
      - ./data/lnd-2:/root/.lnd/

  electrs:
    hostname: electrs
    restart: always
    image: blockstream/esplora:electrs-cd9f90c115751eb9d2bca9a4da89d10d048ae931
    entrypoint: ./electrs_bitcoin/bin/electrs
    command:
      - --electrum-rpc-addr
      - electrs:19001
      - --http-addr
      - electrs:3002
      - --daemon-rpc-addr
      - bitcoind:18443
      - --daemon-dir
      - /home/elements/.elements
      - --cookie
      - regtest:regtest
      - --network
      - regtest
      - --jsonrpc-import
      - -vvvv
    ports:
      - 19001:19001
      - 3002:3002
    volumes:
      - ./data/elements:/home/elements/.elements

  electrs-liquid:
    hostname: electrs-liquid
    restart: always
    image: blockstream/esplora:electrs-cd9f90c115751eb9d2bca9a4da89d10d048ae931
    entrypoint: ./electrs_liquid/bin/electrs
    command:
      - --electrum-rpc-addr
      - electrs-liquid:19002
      - --http-addr
      - electrs-liquid:3003
      - --daemon-rpc-addr
      - elementsd:18884
      - --daemon-dir
      - /home/elements/.elements
      - --cookie
      - regtest:regtest
      - --network
      - liquidregtest
      - --parent-network
      - regtest
      - --jsonrpc-import
      - -vvvv
    ports:
      - 19002:19002
      - 3003:3003
    volumes:
      - ./data/elements:/home/elements/.elements

